package cc.moecraft.icq.plugins.osubot.database.model;

import cc.moecraft.icq.plugins.osubot.database.model.base.BaseDwMap;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dw_map", primaryKey = "id")
public class DwMap extends BaseDwMap<DwMap> {
	
}
