package cc.moecraft.icq.plugins.osubot.database.model;

import io.jboot.db.annotation.Table;
import cc.moecraft.icq.plugins.osubot.database.model.base.BaseDwOsu;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dw_osu", primaryKey = "id")
public class DwOsu extends BaseDwOsu<DwOsu> {
	
}
