package cc.moecraft.icq.plugins.osubot.database.model;

import cc.moecraft.icq.plugins.osubot.database.model.base.BaseHoUserSettings;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "ho_user_settings", primaryKey = "qq_id")
public class HoUserSettings extends BaseHoUserSettings<HoUserSettings>
{

}
