package cc.moecraft.icq.plugins.osubot.database.model;

import io.jboot.db.annotation.Table;
import cc.moecraft.icq.plugins.osubot.database.model.base.BaseHoUserData;

/**
 * Generated by Jboot.
 */
@Table(tableName = "ho_user_data", primaryKey = "osu_id")
public class HoUserData extends BaseHoUserData<HoUserData> {
	
}
