package cc.moecraft.icq.plugins.osubot.database.model;

import cc.moecraft.icq.plugins.osubot.database.model.base.BaseHoUserData;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "ho_user_data", primaryKey = "osu_id")
public class HoUserData extends BaseHoUserData<HoUserData> {
	
}
