package cc.moecraft.icq.plugins.osubot.database.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHoUserData<M extends BaseHoUserData<M>> extends JbootModel<M> implements IBean {

	public void setOsuId(java.lang.Long osuId) {
		set("osu_id", osuId);
	}
	
	public java.lang.Long getOsuId() {
		return getLong("osu_id");
	}

	public void setRecordMode(java.lang.String recordMode) {
		set("record_mode", recordMode);
	}
	
	public java.lang.String getRecordMode() {
		return getStr("record_mode");
	}

	public void setOldLevel(java.lang.Integer oldLevel) {
		set("old_level", oldLevel);
	}
	
	public java.lang.Integer getOldLevel() {
		return getInt("old_level");
	}

	public void setOldPp(java.lang.Double oldPp) {
		set("old_pp", oldPp);
	}
	
	public java.lang.Double getOldPp() {
		return getDouble("old_pp");
	}

	public void setOldAcc(java.lang.Double oldAcc) {
		set("old_acc", oldAcc);
	}
	
	public java.lang.Double getOldAcc() {
		return getDouble("old_acc");
	}

	public void setOldPc(java.lang.Integer oldPc) {
		set("old_pc", oldPc);
	}
	
	public java.lang.Integer getOldPc() {
		return getInt("old_pc");
	}

	public void setOldRank(java.lang.Integer oldRank) {
		set("old_rank", oldRank);
	}
	
	public java.lang.Integer getOldRank() {
		return getInt("old_rank");
	}

	public void setOldTotalScore(java.lang.Long oldTotalScore) {
		set("old_total_score", oldTotalScore);
	}
	
	public java.lang.Long getOldTotalScore() {
		return getLong("old_total_score");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
