package cc.moecraft.icq.plugins.osubot.database.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHoUserSettings<M extends BaseHoUserSettings<M>> extends JbootModel<M> implements IBean {

	public void setQqId(java.lang.Long qqId) {
		set("qq_id", qqId);
	}
	
	public java.lang.Long getQqId() {
		return getLong("qq_id");
	}

	public void setOsuId(java.lang.Long osuId) {
		set("osu_id", osuId);
	}
	
	public java.lang.Long getOsuId() {
		return getLong("osu_id");
	}

	public void setOsuName(java.lang.String osuName) {
		set("osu_name", osuName);
	}
	
	public java.lang.String getOsuName() {
		return getStr("osu_name");
	}

	public void setDefaultMode(java.lang.String defaultMode) {
		set("default_mode", defaultMode);
	}
	
	public java.lang.String getDefaultMode() {
		return getStr("default_mode");
	}

	public void setVerificationState(java.lang.String verificationState) {
		set("verification_state", verificationState);
	}
	
	public java.lang.String getVerificationState() {
		return getStr("verification_state");
	}

	public void setVerificationCode(java.lang.String verificationCode) {
		set("verification_code", verificationCode);
	}
	
	public java.lang.String getVerificationCode() {
		return getStr("verification_code");
	}

	public void setVerificationTime(java.lang.Long verificationTime) {
		set("verification_time", verificationTime);
	}
	
	public java.lang.Long getVerificationTime() {
		return getLong("verification_time");
	}

}
