package cc.moecraft.icq.plugins.osubot.database.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDwMap<M extends BaseDwMap<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setSid(java.lang.Long sid) {
		set("sid", sid);
	}
	
	public java.lang.Long getSid() {
		return getLong("sid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setArtist(java.lang.String artist) {
		set("artist", artist);
	}
	
	public java.lang.String getArtist() {
		return getStr("artist");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setBpm(java.lang.Double bpm) {
		set("bpm", bpm);
	}
	
	public java.lang.Double getBpm() {
		return getDouble("bpm");
	}

	public void setBid(java.lang.Long bid) {
		set("bid", bid);
	}
	
	public java.lang.Long getBid() {
		return getLong("bid");
	}

	public void setMode(java.lang.Integer mode) {
		set("mode", mode);
	}
	
	public java.lang.Integer getMode() {
		return getInt("mode");
	}

	public void setDifficultyRating(java.lang.Double difficultyRating) {
		set("difficulty_rating", difficultyRating);
	}
	
	public java.lang.Double getDifficultyRating() {
		return getDouble("difficulty_rating");
	}

	public void setTotalLength(java.lang.Integer totalLength) {
		set("total_length", totalLength);
	}
	
	public java.lang.Integer getTotalLength() {
		return getInt("total_length");
	}

	public void setCs(java.lang.Double cs) {
		set("cs", cs);
	}
	
	public java.lang.Double getCs() {
		return getDouble("cs");
	}

	public void setDrain(java.lang.Double drain) {
		set("drain", drain);
	}
	
	public java.lang.Double getDrain() {
		return getDouble("drain");
	}

	public void setAccuracy(java.lang.Double accuracy) {
		set("accuracy", accuracy);
	}
	
	public java.lang.Double getAccuracy() {
		return getDouble("accuracy");
	}

	public void setAr(java.lang.Double ar) {
		set("ar", ar);
	}
	
	public java.lang.Double getAr() {
		return getDouble("ar");
	}

	public void setLastUpdated(java.util.Date lastUpdated) {
		set("last_updated", lastUpdated);
	}
	
	public java.util.Date getLastUpdated() {
		return get("last_updated");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setMaxPp(java.lang.Double maxPp) {
		set("max_pp", maxPp);
	}
	
	public java.lang.Double getMaxPp() {
		return getDouble("max_pp");
	}

}
