package cc.moecraft.icq.plugins.osubot.database.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDwOsu<M extends BaseDwOsu<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setPp(java.lang.Double pp) {
		set("pp", pp);
	}
	
	public java.lang.Double getPp() {
		return getDouble("pp");
	}

	public void setAcc(java.lang.Double acc) {
		set("acc", acc);
	}
	
	public java.lang.Double getAcc() {
		return getDouble("acc");
	}

	public void setPc(java.lang.Integer pc) {
		set("pc", pc);
	}
	
	public java.lang.Integer getPc() {
		return getInt("pc");
	}

	public void setTth(java.lang.Integer tth) {
		set("tth", tth);
	}
	
	public java.lang.Integer getTth() {
		return getInt("tth");
	}

	public void setRank(java.lang.Integer rank) {
		set("rank", rank);
	}
	
	public java.lang.Integer getRank() {
		return getInt("rank");
	}

	public void setRankscore(java.lang.String rankscore) {
		set("rankscore", rankscore);
	}
	
	public java.lang.String getRankscore() {
		return getStr("rankscore");
	}

	public void setMode(java.lang.Integer mode) {
		set("mode", mode);
	}
	
	public java.lang.Integer getMode() {
		return getInt("mode");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
